
SNOWPLOW_SESSIONS:
    constraints:
        not_null:
            - session_id

        unique:
            - session_id

        relationships:
            - {from: session_id, to: ref('SNOWPLOW_PAGE_VIEWS'), field: session_id}
