

SNOWPLOW_WEB_EVENTS:
    constraints:
        not_null:
            - domain_userid
            - collector_tstamp
            - domain_sessionid
            - domain_sessionidx
            - page_view_id


        unique:
            - page_view_id

        relationships:
            - {from: page_view_id, to: ref('SNOWPLOW_WEB_PAGE_CONTEXT'), field: page_view_id }

        # ensure there's actually data here
        accepted_values:
            - {field: "case when count(*) > 0 then 'True' else 'False' end", values: ['True']}


SNOWPLOW_WEB_EVENTS_TIME:
    constraints:
        not_null:
            - page_view_id

        unique:
            - page_view_id

        relationships:
            - {from: page_view_id, to: ref('SNOWPLOW_WEB_PAGE_CONTEXT'), field: page_view_id }



SNOWPLOW_WEB_EVENTS_SCROLL_DEPTH:
    constraints:
        not_null:
            - page_view_id

        unique:
            - page_view_id

        relationships:
            - {from: page_view_id, to: ref('SNOWPLOW_WEB_PAGE_CONTEXT'), field: page_view_id }


SNOWPLOW_WEB_PAGE_CONTEXT:
    constraints:
        not_null:
            - root_id
            - page_view_id

        unique:
            - root_id
            - '(page_view_id || root_id)'

SNOWPLOW_PAGE_VIEWS:
    constraints:
        not_null:
            - user_snowplow_domain_id
            - session_id
            - session_index
            - page_view_id

        unique:
            - page_view_id
